'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Avaliacao
    Public Property Id As Integer
    Public Property Descricao As String
    Public Property Nota As Nullable(Of Integer)

    Public Overridable Property Aluguel As ICollection(Of Aluguel) = New HashSet(Of Aluguel)

End Class
