'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Carro
    Public Property Id As Integer
    Public Property Modelo As String
    Public Property Ano As String
    Public Property Placa As String
    Public Property ValorDiaria As Decimal
    Public Property ProprietarioId As Nullable(Of Integer)

    Public Overridable Property Aluguel As ICollection(Of Aluguel) = New HashSet(Of Aluguel)
    Public Overridable Property Usuario As Usuario1

End Class
