'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Carteira
    Public Property Id As Integer
    Public Property Saldo As Nullable(Of Decimal)
    Public Property UsuarioId As Nullable(Of Integer)

    Public Overridable Property Usuario As Usuario1

End Class
