'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class HubcarDbContext
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=HubcarDbContext")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Aluguel() As DbSet(Of Aluguel)
    Public Overridable Property Avaliacao() As DbSet(Of Avaliacao)
    Public Overridable Property Carro() As DbSet(Of Carro)
    Public Overridable Property Carteira() As DbSet(Of Carteira)
    Public Overridable Property TipoUsuario() As DbSet(Of TipoUsuario)
    Public Overridable Property Usuario1Set() As DbSet(Of Usuario1)

End Class
