'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuario1
    Public Property Id As Integer
    Public Property Nome As String
    Public Property Senha As String
    Public Property CPF As String
    Public Property Email As String
    Public Property Cidade As String
    Public Property UF As String
    Public Property TipoUsuarioId As Nullable(Of Integer)

    Public Overridable Property Carro As ICollection(Of Carro) = New HashSet(Of Carro)
    Public Overridable Property Carteira As ICollection(Of Carteira) = New HashSet(Of Carteira)

End Class
